### ISSUE TITLE
OPX assembly build

### ISSUE THREAD

**Issue by reju85** [open-switch/opx-sdi-api#11] opened 2018-01-18 05:56 UTC
Hi,
We are building OPX2.2
When we run package assemble script it also download all the package from scratch  so the build takes lot of time.Is there any way to cache so that minimize the build time?

**Comment by jeffyin-dell** [comment] 2018-02-26 19:35
Duplicate of https://github.com/open-switch/opx-build/issues/25

**Closed as completed by jeffyin-dell** 2018-02-26 19:35 UTC
